baseURL = "https://example.com"
languageCode = "en-us"
title = "Nice is right"
theme = "mini"
defaultContentLanguage = "en"
hasCJKLanguage = true
googleAnalytics = "your-google-analytics-id"

[permalinks]
posts = "/posts/:title/"

[markup.highlight]
guessSyntax = true
style = "emacs"

[markup.tableOfContents]
endLevel = 3
ordered = false
startLevel = 2

[params]
author = "Author"
avatar = "./fran.jpg"
description = "Animals in the pit."
enableRSS = true
enableComments = true
showToc = true
showPowerBy = true
math = false
hiddenPostSummaryInHomePage = false
copyright = " "
