name: build_src

on:
  push:
    branches:
      - master  # Set a branch to deploy
  pull_request:

jobs:
  disp:
    runs-on: ubuntu-20.04
    steps:
      - name: Invoke workflow without inputs
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: build_blog
          repo: segfall/blog
          token: ${{ secrets.PAT }}
